log_file = Filesystem::expand("~/.config/ektoplayer/ektoplayer.log");
cache_dir = Filesystem::expand("~/.cache/ektoplayer");
archive_dir = Filesystem::expand("~/.config/ektoplayer/archives");
database_file = Filesystem::expand("~/.config/ektoplayer/meta.db");
browser_columns = opt_parse_playlist_columns("  number{fg=magenta size=3} artist{fg=blue size=25%} album{fg=red size=30%}   title {fg=yellow size=33%} styles{fg=cyan size=20%} bpm{fg=green size=3 right}");
playlist_columns = opt_parse_playlist_columns("  number{fg=magenta size=3} artist{fg=blue size=25%} album{fg=red size=30%}   title {fg=yellow size=33%} styles{fg=cyan size=20%} bpm{fg=green size=3 right}");
browser_columns_256 = opt_parse_playlist_columns("  number{fg=97 size=3} artist{fg=24 size=25%} album{fg=160 size=30%}   title {fg=178 size=33%} styles{fg=37 size=20%} bpm{fg=28 size=3 right}");
playlist_columns_256 = opt_parse_playlist_columns("  number{fg=97 size=3} artist{fg=24 size=25%} album{fg=160 size=30%}   title {fg=178 size=33%} styles{fg=37 size=20%} bpm{fg=28 size=3 right}");
playinginfo_format_top = opt_parse_playinginfo_format("  '<< '{fg=black} title{fg=yellow,bold} ' >>'{fg=black}");
playinginfo_format_bottom = opt_parse_playinginfo_format("  artist{fg=blue,bold} ' - ' album{fg=red,bold} ' (' year{fg=cyan} ')'");
playinginfo_format_top_256 = opt_parse_playinginfo_format("  '<< '{fg=236} title{fg=178,bold} ' >>'{fg=236}");
playinginfo_format_bottom_256 = opt_parse_playinginfo_format("  artist{fg=24,bold} ' - ' album{fg=160,bold} ' (' year{fg=37} ')'");
