int                           Config :: use_colors = -1;
int                           Config :: small_update_pages = 5;
int                           Config :: playlist_load_newest = 1000;
bool                          Config :: prefetch = true;
bool                          Config :: use_cache = true;
bool                          Config :: tabbar_display = true;
bool                          Config :: playinginfo_display = true;
bool                          Config :: progressbar_display = true;
bool                          Config :: delete_after_extraction = true;
bool                          Config :: auto_extract_to_archive_dir = true;
wchar_t                       Config :: progressbar_rest_char = '~';
wchar_t                       Config :: progressbar_progress_char = '~';
std::string                   Config :: log_file /* will be initialized later */;
std::string                   Config :: temp_dir = "/tmp/.ektoplazm";
std::string                   Config :: cache_dir /* will be initialized later */;
std::string                   Config :: archive_dir /* will be initialized later */;
std::string                   Config :: audio_system = "pulse,alsa,jack,oss";
std::string                   Config :: download_dir = "/tmp";
std::string                   Config :: database_file /* will be initialized later */;
PlaylistColumns               Config :: browser_columns /* will be initialized later */;
PlaylistColumns               Config :: playlist_columns /* will be initialized later */;
PlaylistColumns               Config :: browser_columns_256 /* will be initialized later */;
PlaylistColumns               Config :: playlist_columns_256 /* will be initialized later */;
PlayingInfoFormat             Config :: playinginfo_format_top /* will be initialized later */;
PlayingInfoFormat             Config :: playinginfo_format_bottom /* will be initialized later */;
PlayingInfoFormat             Config :: playinginfo_format_top_256 /* will be initialized later */;
PlayingInfoFormat             Config :: playinginfo_format_bottom_256 /* will be initialized later */;
std::vector<std::string>      Config :: main_widgets = {"playinginfo","tabbar","readline","windows","progressbar"};
std::vector<std::string>      Config :: tabs_widgets = {"splash","playlist","browser","info","help"};
